site_name: EAnacarde Documentation
nav:
  - Welcome: 'index.md'
  - Project: 'project.md'
  - Solution:
    - Overview: 'solution.md'
    - Use case: 'use-case.md'
    - Model: 
      - Entity relationship: 'entity-relationship.md'
    - User story:
      - Definition of Done: 'user-story/definition-of-done.md'
      - US01 Créer utilisateur: 'user-story/us-01-create-user.md' 
      - US02 Login: 'user-story/us-02-login.md'
      - US03 Créer organisation: 'user-story/us-03-create-organization.md'
      - US04 Lire organisation: 'user-story/us-04-read-organization.md'
      - US05 Valider membre: 'user-story/us-05-validate-member.md'
      - US06 Valider organisation: 'user-story/us-06-validate-organization.md'
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: fr
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime